-- Shared Components
INSERT INTO i18n_translations (translation_key, language_code, translation_value) VALUES
('common.filter', 'en', 'Filter'),
('common.filter', 'vi', 'Lọc'),
('common.reset', 'en', 'Reset'),
('common.reset', 'vi', 'Đặt lại'),
('common.loading', 'en', 'Loading...'),
('common.loading', 'vi', 'Đang tải...'),
('common.no_results', 'en', 'No results found'),
('common.no_results', 'vi', 'Không tìm thấy kết quả'),
('common.previous', 'en', 'Previous'),
('common.previous', 'vi', 'Trước'),
('common.next', 'en', 'Next'),
('common.next', 'vi', 'Sau'),
('common.first', 'en', 'First'),
('common.first', 'vi', 'Đầu'),
('common.last', 'en', 'Last'),
('common.last', 'vi', 'Cuối'),
('common.pagination_info', 'en', 'Page {current} of {total}'),
('common.pagination_info', 'vi', 'Trang {current} / {total}'),
('common.active', 'en', 'Active'),
('common.active', 'vi', 'Hoạt động'),
('common.draft', 'en', 'Draft'),
('common.draft', 'vi', 'Bản nháp'),
('common.archived', 'en', 'Archived'),
('common.archived', 'vi', 'Lưu trữ'),
('common.inactive', 'en', 'Inactive'),
('common.inactive', 'vi', 'Không hoạt động'),
('common.unknown', 'en', 'Unknown'),
('common.unknown', 'vi', 'Không xác định'),
('common.uncategorized', 'en', 'Uncategorized'),
('common.uncategorized', 'vi', 'Chưa phân loại'),
('common.description', 'en', 'Description'),
('common.description', 'vi', 'Mô tả'),
('common.actions', 'en', 'Actions'),
('common.actions', 'vi', 'Hành động'),
('common.edit', 'en', 'Edit'),
('common.edit', 'vi', 'Sửa'),
('common.delete', 'en', 'Delete'),
('common.delete', 'vi', 'Xóa'),
('common.create', 'en', 'Create'),
('common.create', 'vi', 'Tạo'),
('common.save_changes', 'en', 'Save Changes'),
('common.save_changes', 'vi', 'Lưu thay đổi'),
('common.saving', 'en', 'Saving...'),
('common.saving', 'vi', 'Đang lưu...'),
('common.cancel', 'en', 'Cancel'),
('common.cancel', 'vi', 'Hủy'),
('common.activate', 'en', 'Activate'),
('common.activate', 'vi', 'Kích hoạt'),
('common.deactivate', 'en', 'Deactivate'),
('common.deactivate', 'vi', 'Vô hiệu hóa'),
('common.default', 'en', 'Default'),
('common.default', 'vi', 'Mặc định'),
('common.all', 'en', 'All'),
('common.all', 'vi', 'Tất cả'),

-- Product Management
('admin.manage.products.title', 'en', 'Product Management'),
('admin.manage.products.title', 'vi', 'Quản lý Sản phẩm'),
('admin.manage.products.subtitle', 'en', 'Manage your catalog, prices, and inventory.'),
('admin.manage.products.subtitle', 'vi', 'Quản lý danh mục, giá cả và kho hàng.'),
('admin.manage.products.add_new', 'en', 'Add New Product'),
('admin.manage.products.add_new', 'vi', 'Thêm sản phẩm'),
('admin.manage.products.search_placeholder', 'en', 'Search products...'),
('admin.manage.products.search_placeholder', 'vi', 'Tìm kiếm sản phẩm...'),
('admin.forms.product.brand', 'en', 'Brand'),
('admin.forms.product.brand', 'vi', 'Thương hiệu'),
('admin.manage.products.brand_placeholder', 'en', 'Filter by brand'),
('admin.manage.products.brand_placeholder', 'vi', 'Lọc theo thương hiệu'),
('product.category', 'en', 'Category'),
('product.category', 'vi', 'Danh mục'),
('admin.manage.products.all_categories', 'en', 'All Categories'),
('admin.manage.products.all_categories', 'vi', 'Tất cả danh mục'),
('common.status', 'en', 'Status'),
('common.status', 'vi', 'Trạng thái'),
('admin.manage.products.all_statuses', 'en', 'All Statuses'),
('admin.manage.products.all_statuses', 'vi', 'Tất cả trạng thái'),
('product.price_range', 'en', 'Price Range'),
('product.price_range', 'vi', 'Khoảng giá'),
('admin.manage.products.min_price', 'en', 'Min'),
('admin.manage.products.min_price', 'vi', 'Min'),
('admin.manage.products.max_price', 'en', 'Max'),
('admin.manage.products.max_price', 'vi', 'Max'),
('admin.manage.products.no_results', 'en', 'No products found'),
('admin.manage.products.no_results', 'vi', 'Không tìm thấy sản phẩm'),
('admin.manage.products.no_results_desc', 'en', 'Try adjusting your search or filters to find what you are looking for.'),
('admin.manage.products.no_results_desc', 'vi', 'Thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn.'),
('admin.manage.products.columns.product', 'en', 'Product'),
('admin.manage.products.columns.product', 'vi', 'Sản phẩm'),
('admin.manage.products.columns.sku', 'en', 'SKU'),
('admin.manage.products.columns.sku', 'vi', 'SKU'),
('admin.manage.products.columns.brand', 'en', 'Brand'),
('admin.manage.products.columns.brand', 'vi', 'Thương hiệu'),
('admin.manage.products.columns.category', 'en', 'Category'),
('admin.manage.products.columns.category', 'vi', 'Danh mục'),
('admin.manage.products.columns.price', 'en', 'Price'),
('admin.manage.products.columns.price', 'vi', 'Giá'),
('admin.manage.products.columns.stock', 'en', 'Stock'),
('admin.manage.products.columns.stock', 'vi', 'Kho'),
('admin.manage.products.columns.status', 'en', 'Status'),
('admin.manage.products.columns.status', 'vi', 'Trạng thái'),
('product.no_description', 'en', 'No description available'),
('product.no_description', 'vi', 'Không có mô tả'),
('admin.forms.product.variants', 'en', 'Has Variants'),
('admin.forms.product.variants', 'vi', 'Có biến thể'),
('admin.forms.product.edit_title', 'en', 'Edit Product'),
('admin.forms.product.edit_title', 'vi', 'Sửa sản phẩm'),
('admin.products', 'en', 'Product'),
('admin.products', 'vi', 'Sản phẩm'),
('media.delete_confirm', 'en', 'Are you sure you want to delete {type} "{name}"? This action cannot be undone.'),
('media.delete_confirm', 'vi', 'Bạn có chắc muốn xóa {type} "{name}"? Hành động này không thể hoàn tác.'),

-- Category Management
('admin.manage.categories.title', 'en', 'Category Management'),
('admin.manage.categories.title', 'vi', 'Quản lý Danh mục'),
('admin.manage.categories.subtitle', 'en', 'Organize your products with categories.'),
('admin.manage.categories.subtitle', 'vi', 'Tổ chức sản phẩm theo danh mục.'),
('admin.manage.categories.add_new', 'en', 'Add New Category'),
('admin.manage.categories.add_new', 'vi', 'Thêm danh mục'),
('admin.manage.categories.search_placeholder', 'en', 'Search categories...'),
('admin.manage.categories.search_placeholder', 'vi', 'Tìm kiếm danh mục...'),
('admin.manage.categories.no_results', 'en', 'No categories found'),
('admin.manage.categories.no_results', 'vi', 'Không tìm thấy danh mục'),
('admin.manage.categories.no_results_desc', 'en', 'Try adjusting your filters.'),
('admin.manage.categories.no_results_desc', 'vi', 'Thử điều chỉnh bộ lọc.'),
('admin.forms.category.display_order', 'en', 'Order'),
('admin.forms.category.display_order', 'vi', 'Thứ tự'),
('admin.forms.category.edit_title', 'en', 'Edit Category'),
('admin.forms.category.edit_title', 'vi', 'Sửa danh mục'),

-- Language Management
('admin.i18n.languages.title', 'en', 'Language Management'),
('admin.i18n.languages.title', 'vi', 'Quản lý Ngôn ngữ'),
('admin.i18n.languages.subtitle', 'en', 'Manage supported languages for your store.'),
('admin.i18n.languages.subtitle', 'vi', 'Quản lý các ngôn ngữ hỗ trợ.'),
('admin.i18n.languages.add_new', 'en', 'Add Language'),
('admin.i18n.languages.add_new', 'vi', 'Thêm ngôn ngữ'),
('admin.i18n.languages.search_placeholder', 'en', 'Search languages...'),
('admin.i18n.languages.search_placeholder', 'vi', 'Tìm kiếm ngôn ngữ...'),
('admin.i18n.languages.columns.flag', 'en', 'Flag'),
('admin.i18n.languages.columns.flag', 'vi', 'Cờ'),
('admin.i18n.languages.columns.name', 'en', 'Name'),
('admin.i18n.languages.columns.name', 'vi', 'Tên'),
('admin.i18n.languages.columns.code', 'en', 'Code'),
('admin.i18n.languages.columns.code', 'vi', 'Mã'),
('admin.i18n.languages.columns.status', 'en', 'Status'),
('admin.i18n.languages.columns.status', 'vi', 'Trạng thái'),
('admin.i18n.languages.columns.default', 'en', 'Default'),
('admin.i18n.languages.columns.default', 'vi', 'Mặc định'),
('admin.i18n.languages.columns.order', 'en', 'Order'),
('admin.i18n.languages.columns.order', 'vi', 'Thứ tự'),
('admin.i18n.languages.make_default', 'en', 'Make Default'),
('admin.i18n.languages.make_default', 'vi', 'Đặt mặc định'),
('admin.i18n.languages.edit_title', 'en', 'Edit Language'),
('admin.i18n.languages.edit_title', 'vi', 'Sửa ngôn ngữ'),
('admin.i18n.languages.add_title', 'en', 'Add Language'),
('admin.i18n.languages.add_title', 'vi', 'Thêm ngôn ngữ'),
('admin.i18n.languages.fields.code', 'en', 'Code (ISO 639-1)'),
('admin.i18n.languages.fields.code', 'vi', 'Mã (ISO 639-1)'),
('admin.i18n.languages.fields.code_placeholder', 'en', 'e.g. en, vi, fr'),
('admin.i18n.languages.fields.code_placeholder', 'vi', 'vd: en, vi, fr'),
('admin.i18n.languages.fields.order', 'en', 'Display Order'),
('admin.i18n.languages.fields.order', 'vi', 'Thứ tự hiển thị'),
('admin.i18n.languages.fields.name', 'en', 'Language Name'),
('admin.i18n.languages.fields.name', 'vi', 'Tên ngôn ngữ'),
('admin.i18n.languages.fields.name_placeholder', 'en', 'e.g. English'),
('admin.i18n.languages.fields.name_placeholder', 'vi', 'vd: Tiếng Việt'),
('admin.i18n.languages.fields.flag', 'en', 'Flag Icon URL'),
('admin.i18n.languages.fields.flag', 'vi', 'URL Cờ'),
('admin.i18n.languages.fields.flag_placeholder', 'en', 'https://...'),
('admin.i18n.languages.fields.flag_placeholder', 'vi', 'https://...'),
('admin.i18n.languages.delete_confirm', 'en', 'Are you sure you want to delete language "{name}"?'),
('admin.i18n.languages.delete_confirm', 'vi', 'Bạn có chắc muốn xóa ngôn ngữ "{name}"?'),

-- Translation Management
('admin.i18n.translations.title', 'en', 'Translations'),
('admin.i18n.translations.title', 'vi', 'Dịch thuật'),
('admin.i18n.translations.subtitle', 'en', 'Manage translation keys and values.'),
('admin.i18n.translations.subtitle', 'vi', 'Quản lý các khóa dịch và giá trị.'),
('admin.i18n.translations.add_key', 'en', 'Add Key'),
('admin.i18n.translations.add_key', 'vi', 'Thêm khóa'),
('admin.i18n.translations.search_placeholder', 'en', 'Search keys or values...'),
('admin.i18n.translations.search_placeholder', 'vi', 'Tìm kiếm khóa hoặc giá trị...'),
('admin.i18n.translations.keys_found', 'en', '{count} Keys Found'),
('admin.i18n.translations.keys_found', 'vi', 'Tìm thấy {count} khóa'),
('admin.i18n.translations.columns.key', 'en', 'Translation Key'),
('admin.i18n.translations.columns.key', 'vi', 'Khóa dịch'),
('admin.translations', 'en', 'Translations'),
('admin.translations', 'vi', 'Bản dịch'),
('admin.i18n.translations.add_key_title', 'en', 'Add New Translation Key'),
('admin.i18n.translations.add_key_title', 'vi', 'Thêm khóa dịch mới'),
('admin.i18n.translations.edit_key_title', 'en', 'Edit Translation Key'),
('admin.i18n.translations.edit_key_title', 'vi', 'Sửa khóa dịch'),
('admin.i18n.translations.fields.key_name', 'en', 'Key Name'),
('admin.i18n.translations.fields.key_name', 'vi', 'Tên khóa'),
('admin.i18n.translations.same_as_default', 'en', 'Same as default...'),
('admin.i18n.translations.same_as_default', 'vi', 'Giống mặc định...'),
('admin.i18n.translations.delete_key_confirm', 'en', 'Are you sure you want to delete key "{key}"?'),
('admin.i18n.translations.delete_key_confirm', 'vi', 'Bạn có chắc muốn xóa khóa "{key}"?')
ON CONFLICT (translation_key, language_code) DO NOTHING;
